// Script-side projection of the checked-in component inventory. Gallery code
// cannot import repository JSON at runtime; verify-coverage.mjs rejects drift.
export const REGISTERED_SURFACES = [
  "Accordion",
  "Alert",
  "AlertDialog",
  "Attachment",
  "Avatar",
  "BarChart",
  "Badge",
  "Breadcrumb",
  "Bubble",
  "Button",
  "Calendar",
  "Carousel",
  "Checkbox",
  "Clipboard",
  "Collapsible",
  "ColorPicker",
  "Combobox",
  "Command",
  "DatePicker",
  "DataTable",
  "DescriptionList",
  "Dialog",
  "DropdownButton",
  "Editor",
  "Empty",
  "Form",
  "GroupBox",
  "HoverCard",
  "Icon",
  "Image",
  "Input",
  "InputGroup",
  "Kbd",
  "Label",
  "Link",
  "List",
  "MenuBar",
  "Marker",
  "Message",
  "MessageScroller",
  "NumberInput",
  "NativeMenuTrigger",
  "Notification",
  "OtpInput",
  "Pagination",
  "Popover",
  "Progress",
  "Questionnaire",
  "Radio",
  "Rating",
  "Resizable",
  "Scroll",
  "Scrollbar",
  "Separator",
  "Select",
  "Sheet",
  "ShimmerText",
  "Settings",
  "Sidebar",
  "Skeleton",
  "Slider",
  "Spinner",
  "StatusBar",
  "Switch",
  "Tag",
  "Tab",
  "TabBar",
  "Table",
  "Text",
  "Textarea",
  "TimeField",
  "Stepper",
  "Toggle",
  "Toolbar",
  "Tooltip",
  "Tree",
];

/** @param {string} surface @returns {{ status: "registered" } | null} */
export function surfaceStatus(surface) {
  if (REGISTERED_SURFACES.includes(surface)) return { status: "registered" };
  return null;
}
