use super::{Op, enum_method};
use gpui_component::input::InputContentType;
use gpui_shell::MethodDescriptor;

pub(super) fn method() -> MethodDescriptor {
    enum_method(
        "content_type",
        &[
            "name",
            "name_prefix",
            "given_name",
            "middle_name",
            "family_name",
            "name_suffix",
            "nickname",
            "job_title",
            "organization_name",
            "location",
            "full_street_address",
            "street_address_line1",
            "street_address_line2",
            "address_city",
            "address_state",
            "address_city_and_state",
            "sublocality",
            "country_name",
            "postal_code",
            "telephone_number",
            "email_address",
            "url",
            "credit_card_number",
            "credit_card_name",
            "credit_card_given_name",
            "credit_card_middle_name",
            "credit_card_family_name",
            "credit_card_security_code",
            "credit_card_expiration",
            "credit_card_expiration_month",
            "credit_card_expiration_year",
            "credit_card_type",
            "username",
            "password",
            "new_password",
            "one_time_code",
            "shipment_tracking_number",
            "flight_number",
            "date_time",
            "birthdate",
            "birthdate_day",
            "birthdate_month",
            "birthdate_year",
            "cellular_eid",
            "cellular_imei",
        ],
        "Sets the native content type; names follow InputContentType in snake_case.",
        |value| {
            Some(Op::ContentType(match value {
                "name" => InputContentType::Name,
                "name_prefix" => InputContentType::NamePrefix,
                "given_name" => InputContentType::GivenName,
                "middle_name" => InputContentType::MiddleName,
                "family_name" => InputContentType::FamilyName,
                "name_suffix" => InputContentType::NameSuffix,
                "nickname" => InputContentType::Nickname,
                "job_title" => InputContentType::JobTitle,
                "organization_name" => InputContentType::OrganizationName,
                "location" => InputContentType::Location,
                "full_street_address" => InputContentType::FullStreetAddress,
                "street_address_line1" => InputContentType::StreetAddressLine1,
                "street_address_line2" => InputContentType::StreetAddressLine2,
                "address_city" => InputContentType::AddressCity,
                "address_state" => InputContentType::AddressState,
                "address_city_and_state" => InputContentType::AddressCityAndState,
                "sublocality" => InputContentType::Sublocality,
                "country_name" => InputContentType::CountryName,
                "postal_code" => InputContentType::PostalCode,
                "telephone_number" => InputContentType::TelephoneNumber,
                "email_address" => InputContentType::EmailAddress,
                "url" => InputContentType::Url,
                "credit_card_number" => InputContentType::CreditCardNumber,
                "credit_card_name" => InputContentType::CreditCardName,
                "credit_card_given_name" => InputContentType::CreditCardGivenName,
                "credit_card_middle_name" => InputContentType::CreditCardMiddleName,
                "credit_card_family_name" => InputContentType::CreditCardFamilyName,
                "credit_card_security_code" => InputContentType::CreditCardSecurityCode,
                "credit_card_expiration" => InputContentType::CreditCardExpiration,
                "credit_card_expiration_month" => InputContentType::CreditCardExpirationMonth,
                "credit_card_expiration_year" => InputContentType::CreditCardExpirationYear,
                "credit_card_type" => InputContentType::CreditCardType,
                "username" => InputContentType::Username,
                "password" => InputContentType::Password,
                "new_password" => InputContentType::NewPassword,
                "one_time_code" => InputContentType::OneTimeCode,
                "shipment_tracking_number" => InputContentType::ShipmentTrackingNumber,
                "flight_number" => InputContentType::FlightNumber,
                "date_time" => InputContentType::DateTime,
                "birthdate" => InputContentType::Birthdate,
                "birthdate_day" => InputContentType::BirthdateDay,
                "birthdate_month" => InputContentType::BirthdateMonth,
                "birthdate_year" => InputContentType::BirthdateYear,
                "cellular_eid" => InputContentType::CellularEid,
                "cellular_imei" => InputContentType::CellularImei,
                _ => return None,
            }))
        },
    )
}
